name: "Play with GitHub Actions"
description: "Make some tests"
runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Cache dependencies
    id: cache
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install dependencies from requirements.txt
    shell: bash
    if: steps.cache.outputs.cache-hit != 'true'
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run Python script main.py
    shell: bash
    run: python main.py
