name: "Play with GitHub Actions"
description: "Make some tests"
inputs:
  ENAC_IT4R_CD_environment:
    description: "Deployment environment"
    required: true
runs:
  using: "composite"
  steps:
  - name: Checkout play with gh action
    uses: actions/checkout@v3
    with:
      repository: sbancal/play-with-gh-action
      ref: main
      path: play-with-gh-action

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Cache dependencies
    id: cache
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('play-with-gh-action/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install dependencies from requirements.txt
    shell: bash
    if: steps.cache.outputs.cache-hit != 'true'
    run: |
      python -m pip install --upgrade pip
      pip install -r play-with-gh-action/requirements.txt

  - name: Run Python script main.py
    shell: bash
    run: python play-with-gh-action/main.py --env ${{inputs.ENAC_IT4R_CD_environment}}
